In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame(np.random.randn(4, 4), columns=list('ABCD'))
df

          A         B         C         D
0  1.051199  0.192167 -1.500187 -0.357033
1 -0.509266 -1.345325 -1.281407  1.546608
2 -1.704608  0.413110 -0.256528  0.713798
3  0.549814  0.793543  0.280693 -0.279466

In [10]:
type(df['A'])

pandas.core.series.Series

In [13]:
dir(pd.core.series.Series)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__int__',
 '__invert__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_agg_by_level',
 '_align_frame',
 '_align_series',
 '_allow_index_ops',
 '_at',
 '_binop',
 '_box_item_values',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_create_indexer',
 '_dir_additions',
 '_dir_deletions',
 '_expand_axes',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_numeric_data',
 '_get_repr',
 '_get_val_at',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_iat',
 '_iget_item_cache',
 '_iloc',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_datelike_mixed_type',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_loc',
 '_make_cat_accessor',
 '_make_dt_accessor',
 '_make_str_accessor',
 '_maybe_box',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_subtyp',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'as_blocks',
 'as_matrix',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'autocorr',
 'axes',
 'base',
 'between',
 'between_time',
 'bfill',
 'blocks',
 'bool',
 'cat',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compound',
 'compress',
 'consolidate',
 'convert_objects',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'data',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dt',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_array',
 'from_csv',
 'ftype',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_value',
 'get_values',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iget',
 'iget_value',
 'iloc',
 'imag',
 'index',
 'interpolate',
 'irow',
 'is_copy',
 'is_time_series',
 'isin',
 'isnull',
 'item',
 'items',
 'itemsize',
 'iteritems',
 'iterkv',
 'ix',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'nonzero',
 'notnull',
 'nsmallest',
 'nunique',
 'order',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'ptp',
 'put',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'real',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'reshape',
 'rfloordiv',
 'rmod',
 'rmul',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'select',
 'sem',
 'set_axis',
 'set_value',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort',
 'sort_index',
 'sort_values',
 'sortlevel',
 'squeeze',
 'std',
 'str',
 'strides',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_msgpack',
 'to_period',
 'to_pickle',
 'to_sparse',
 'to_sql',
 'to_string',
 'to_timestamp',
 'tolist',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'valid',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [14]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
A,0.474818,1.833454,0.812475,0.393175,0.067635,-0.766986,-0.538515,0.383452,0.718059,0.201588,...,-0.091959,2.196001,-0.903082,0.770507,-0.449751,1.492151,1.311757,1.993769,1.125900,-1.183126
B,-0.102216,1.077390,-0.069935,-0.011882,-1.585122,-0.193388,0.156209,-0.716297,1.369110,0.619699,...,2.190731,0.137946,1.125362,0.803269,-0.903398,-1.185187,-1.190296,0.314773,-0.175785,0.725911
C,-0.217280,-0.781302,0.993767,1.193723,-1.051585,-1.546782,-0.311387,0.379094,0.058798,-0.656257,...,-1.242113,-0.231568,-0.868250,0.937843,-0.472557,0.456745,-1.181060,-1.012238,0.443722,-1.225322
D,-1.684319,1.132882,-0.107669,0.184792,0.337782,-2.572206,-0.732694,0.053774,0.407773,1.736705,...,0.957272,0.395087,-0.147720,0.227706,0.197107,-0.917313,0.085927,-0.348145,0.620163,-0.458565

In [15]:
df.to_dict()

{'A': {0: 0.47481787017301458,
  1: 1.8334543756119777,
  2: 0.81247547897563055,
  3: 0.39317512438137697,
  4: 0.067635364254871252,
  5: -0.76698613807979787,
  6: -0.53851496575938562,
  7: 0.38345220862413332,
  8: 0.71805887905765375,
  9: 0.20158773265912674,
  10: -0.24448091632580685,
  11: 2.0798856659862177,
  12: 0.74219720302629233,
  13: -0.85934852933090389,
  14: 1.7378063307350811,
  15: 0.89521604556992085,
  16: -0.76385306373042849,
  17: -0.87296761806614942,
  18: -0.36134156908170773,
  19: -0.78354289906687447,
  20: 1.2254298914526307,
  21: 1.0144785145540383,
  22: -0.17478479651582074,
  23: -0.13353282279931467,
  24: -0.86210877704356315,
  25: -0.39535980806769777,
  26: 1.4269409051344661,
  27: 0.13107927275448966,
  28: 0.29498931482418711,
  29: 0.46698033225576735,
  30: -0.28104887172518511,
  31: 1.5661813985396631,
  32: 1.6314751352792862,
  33: 0.70069590198707188,
  34: 0.66272585821398045,
  35: -1.9037096205528183,
  36: 0.94931201304093416,
  37: 0.23981452497329267,
  38: 1.069176560845537,
  39: 0.75018101546445926,
  40: -0.091958705776826521,
  41: 2.1960007404013764,
  42: -0.90308152812817954,
  43: 0.77050652307768408,
  44: -0.44975083676139438,
  45: 1.4921513848423185,
  46: 1.3117567839575828,
  47: 1.9937691120463501,
  48: 1.1258996458573842,
  49: -1.1831259285511804},
 'B': {0: -0.10221616943436385,
  1: 1.0773902669598481,
  2: -0.069934696546135433,
  3: -0.011881887491306756,
  4: -1.5851222846485944,
  5: -0.19338777321598169,
  6: 0.15620922481426863,
  7: -0.71629701640300825,
  8: 1.3691098505693597,
  9: 0.61969892185728226,
  10: 0.65487074595452466,
  11: -0.56970598948089546,
  12: 0.82221407667430446,
  13: -0.15816812681078249,
  14: -0.28075752069491583,
  15: 0.2413192869469685,
  16: 0.018943616578232288,
  17: -0.53207712406441865,
  18: -0.11502466328102137,
  19: -2.5461970019086757,
  20: -0.13293357088934876,
  21: 0.19188339749379524,
  22: -0.46092041854560417,
  23: 0.029009598284875749,
  24: -0.24585318448061985,
  25: 0.2785886118193181,
  26: 2.4837344988122525,
  27: -0.31084661655703655,
  28: 1.6054590260766706,
  29: 0.63670299920911499,
  30: 0.74137287998419199,
  31: 2.2229965103777141,
  32: -0.46626931786300468,
  33: -0.22333444940296007,
  34: -1.0355747079681137,
  35: 0.69320103828637625,
  36: -0.90689355700535512,
  37: 0.62647653717832774,
  38: -0.32590496338164643,
  39: -0.3850406394940315,
  40: 2.1907314870662802,
  41: 0.13794638891429575,
  42: 1.1253618120083939,
  43: 0.80326854179947227,
  44: -0.90339831790808656,
  45: -1.1851872263508649,
  46: -1.1902959335491063,
  47: 0.31477263502810054,
  48: -0.17578514942005152,
  49: 0.72591133660143603},
 'C': {0: -0.21728044101746338,
  1: -0.78130217967795135,
  2: 0.993767468088954,
  3: 1.1937232690863384,
  4: -1.0515846299499978,
  5: -1.5467816304614579,
  6: -0.31138721709644263,
  7: 0.37909356461681076,
  8: 0.058797710962931245,
  9: -0.65625744873467706,
  10: 0.85490582710398488,
  11: -0.88055348457224836,
  12: -0.85044797891328505,
  13: 0.58097439284367747,
  14: -0.12071977415511764,
  15: 0.69930428522078159,
  16: 0.54825901875872607,
  17: -0.15415606119155378,
  18: 0.04407238307092548,
  19: -0.70636665382827823,
  20: -0.61764114704817719,
  21: -0.77245124609530547,
  22: -0.29486834434690046,
  23: -1.4493369572806487,
  24: 0.75841221916382884,
  25: -0.22892696335989124,
  26: -0.93249826541431713,
  27: 0.1669377057252826,
  28: 0.75727586220288523,
  29: -0.43042822833110511,
  30: 0.56578624083187468,
  31: -0.68346665739490153,
  32: 0.60792426741211614,
  33: -0.26358248900134496,
  34: 2.2604836427721766,
  35: -0.84705650353477446,
  36: -2.2067755470043151,
  37: -0.47456157350298356,
  38: 0.11783308943141228,
  39: 0.81497392025174087,
  40: -1.2421127516581127,
  41: -0.2315684021887946,
  42: -0.8682500155832209,
  43: 0.93784269896500161,
  44: -0.47255723278109274,
  45: 0.45674534881132528,
  46: -1.1810602743613496,
  47: -1.0122375546642561,
  48: 0.4437220894371966,
  49: -1.2253217255198017},
 'D': {0: -1.6843192349801024,
  1: 1.1328820730905611,
  2: -0.10766864581110165,
  3: 0.18479236034998281,
  4: 0.33778176692652323,
  5: -2.5722064015341912,
  6: -0.73269357602711205,
  7: 0.053773552219342963,
  8: 0.40777251666234215,
  9: 1.7367051918687693,
  10: 0.91576890345131368,
  11: -0.90292321976170209,
  12: 0.36246866362080959,
  13: 0.51218614651043726,
  14: -0.7279714089954914,
  15: 1.6834464730672112,
  16: 0.33849597046365359,
  17: 1.1829536942032843,
  18: 0.87948021870726656,
  19: 0.97282230515189705,
  20: -0.51042198274348372,
  21: 0.82399350124503001,
  22: -1.0238547539553331,
  23: 0.010975916055661681,
  24: -1.5058343238174305,
  25: -0.81754316389535509,
  26: -0.55103757103095274,
  27: 1.2958909063601494,
  28: -0.84819644925880988,
  29: 1.3851860933823463,
  30: 0.58722012460378825,
  31: 1.1577076029583198,
  32: 0.71523723545618256,
  33: 1.4212720753058412,
  34: -0.23881378449251381,
  35: 0.016639732030480175,
  36: 0.69645567218527393,
  37: 1.2655020666742329,
  38: -1.1144619578007995,
  39: 0.3348001468898596,
  40: 0.95727207588991958,
  41: 0.3950874774903243,
  42: -0.14772042620597692,
  43: 0.22770585821857073,
  44: 0.19710707210387562,
  45: -0.91731326224963983,
  46: 0.08592655273342957,
  47: -0.34814547164519627,
  48: 0.62016333066265095,
  49: -0.45856519880423446}}

In [16]:
df.to_latex

<bound method DataFrame.to_latex of            A         B         C         D
0   0.474818 -0.102216 -0.217280 -1.684319
1   1.833454  1.077390 -0.781302  1.132882
2   0.812475 -0.069935  0.993767 -0.107669
3   0.393175 -0.011882  1.193723  0.184792
4   0.067635 -1.585122 -1.051585  0.337782
5  -0.766986 -0.193388 -1.546782 -2.572206
6  -0.538515  0.156209 -0.311387 -0.732694
7   0.383452 -0.716297  0.379094  0.053774
8   0.718059  1.369110  0.058798  0.407773
9   0.201588  0.619699 -0.656257  1.736705
10 -0.244481  0.654871  0.854906  0.915769
11  2.079886 -0.569706 -0.880553 -0.902923
12  0.742197  0.822214 -0.850448  0.362469
13 -0.859349 -0.158168  0.580974  0.512186
14  1.737806 -0.280758 -0.120720 -0.727971
15  0.895216  0.241319  0.699304  1.683446
16 -0.763853  0.018944  0.548259  0.338496
17 -0.872968 -0.532077 -0.154156  1.182954
18 -0.361342 -0.115025  0.044072  0.879480
19 -0.783543 -2.546197 -0.706367  0.972822
20  1.225430 -0.132934 -0.617641 -0.510422
21  1.014479  0.191883 -0.772451  0.823994
22 -0.174785 -0.460920 -0.294868 -1.023855
23 -0.133533  0.029010 -1.449337  0.010976
24 -0.862109 -0.245853  0.758412 -1.505834
25 -0.395360  0.278589 -0.228927 -0.817543
26  1.426941  2.483734 -0.932498 -0.551038
27  0.131079 -0.310847  0.166938  1.295891
28  0.294989  1.605459  0.757276 -0.848196
29  0.466980  0.636703 -0.430428  1.385186
30 -0.281049  0.741373  0.565786  0.587220
31  1.566181  2.222997 -0.683467  1.157708
32  1.631475 -0.466269  0.607924  0.715237
33  0.700696 -0.223334 -0.263582  1.421272
34  0.662726 -1.035575  2.260484 -0.238814
35 -1.903710  0.693201 -0.847057  0.016640
36  0.949312 -0.906894 -2.206776  0.696456
37  0.239815  0.626477 -0.474562  1.265502
38  1.069177 -0.325905  0.117833 -1.114462
39  0.750181 -0.385041  0.814974  0.334800
40 -0.091959  2.190731 -1.242113  0.957272
41  2.196001  0.137946 -0.231568  0.395087
42 -0.903082  1.125362 -0.868250 -0.147720
43  0.770507  0.803269  0.937843  0.227706
44 -0.449751 -0.903398 -0.472557  0.197107
45  1.492151 -1.185187  0.456745 -0.917313
46  1.311757 -1.190296 -1.181060  0.085927
47  1.993769  0.314773 -1.012238 -0.348145
48  1.125900 -0.175785  0.443722  0.620163
49 -1.183126  0.725911 -1.225322 -0.458565>

In [19]:
s = df['A']
s[0]

0.47481787017301458

In [20]:
df.keys()

Index(['A', 'B', 'C', 'D'], dtype='object')

In [21]:
df.T.keys()

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
           dtype='int64')

In [23]:
df.T.rank()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
A,4,4,3,3,3,3,2,4,3,2,...,2,4,1,2,3,4,4,4,4,2
B,3,2,2,1,1,4,4,1,4,3,...,4,2,4,3,1,1,1,3,1,4
C,2,1,4,4,2,2,3,3,1,1,...,1,1,2,4,2,3,2,1,2,1
D,1,3,1,2,4,1,1,2,2,4,...,3,3,3,1,4,2,3,2,3,3

In [27]:
list(map(lambda x: x, df['A']))

[0.47481787017301458,
 1.8334543756119777,
 0.81247547897563055,
 0.39317512438137697,
 0.067635364254871252,
 -0.76698613807979787,
 -0.53851496575938562,
 0.38345220862413332,
 0.71805887905765375,
 0.20158773265912674,
 -0.24448091632580685,
 2.0798856659862177,
 0.74219720302629233,
 -0.85934852933090389,
 1.7378063307350811,
 0.89521604556992085,
 -0.76385306373042849,
 -0.87296761806614942,
 -0.36134156908170773,
 -0.78354289906687447,
 1.2254298914526307,
 1.0144785145540383,
 -0.17478479651582074,
 -0.13353282279931467,
 -0.86210877704356315,
 -0.39535980806769777,
 1.4269409051344661,
 0.13107927275448966,
 0.29498931482418711,
 0.46698033225576735,
 -0.28104887172518511,
 1.5661813985396631,
 1.6314751352792862,
 0.70069590198707188,
 0.66272585821398045,
 -1.9037096205528183,
 0.94931201304093416,
 0.23981452497329267,
 1.069176560845537,
 0.75018101546445926,
 -0.091958705776826521,
 2.1960007404013764,
 -0.90308152812817954,
 0.77050652307768408,
 -0.44975083676139438,
 1.4921513848423185,
 1.3117567839575828,
 1.9937691120463501,
 1.1258996458573842,
 -1.1831259285511804]

In [28]:
list(df['A'])

[0.47481787017301458,
 1.8334543756119777,
 0.81247547897563055,
 0.39317512438137697,
 0.067635364254871252,
 -0.76698613807979787,
 -0.53851496575938562,
 0.38345220862413332,
 0.71805887905765375,
 0.20158773265912674,
 -0.24448091632580685,
 2.0798856659862177,
 0.74219720302629233,
 -0.85934852933090389,
 1.7378063307350811,
 0.89521604556992085,
 -0.76385306373042849,
 -0.87296761806614942,
 -0.36134156908170773,
 -0.78354289906687447,
 1.2254298914526307,
 1.0144785145540383,
 -0.17478479651582074,
 -0.13353282279931467,
 -0.86210877704356315,
 -0.39535980806769777,
 1.4269409051344661,
 0.13107927275448966,
 0.29498931482418711,
 0.46698033225576735,
 -0.28104887172518511,
 1.5661813985396631,
 1.6314751352792862,
 0.70069590198707188,
 0.66272585821398045,
 -1.9037096205528183,
 0.94931201304093416,
 0.23981452497329267,
 1.069176560845537,
 0.75018101546445926,
 -0.091958705776826521,
 2.1960007404013764,
 -0.90308152812817954,
 0.77050652307768408,
 -0.44975083676139438,
 1.4921513848423185,
 1.3117567839575828,
 1.9937691120463501,
 1.1258996458573842,
 -1.1831259285511804]

In [31]:
tmp = pd.DataFrame()

In [32]:
tmp

Empty DataFrame
Columns: []
Index: []

In [33]:
assert 1==2

AssertionError:

In [40]:
df.columns[0].lower()

'a'

In [46]:
'a' in list(map(lambda x: x.lower(), df.columns))

True

In [47]:
df['A'][0]

0.47481787017301458

In [53]:
df.T[0]['A']

0.47481787017301458

In [54]:
df[:3]

          A         B         C         D
0  0.474818 -0.102216 -0.217280 -1.684319
1  1.833454  1.077390 -0.781302  1.132882
2  0.812475 -0.069935  0.993767 -0.107669

In [56]:
df[3]

KeyError: 3

In [34]:
df.shape[0]

50

In [29]:
list(df.T[1])

[1.6030130724583589,
 0.77279496401212366,
 -0.63420677041027862,
 0.8551656994317981]

In [8]:
list(df.columns)

['A', 'B', 'C', 'D']

In [12]:
df.[]

          A         B         C         D
0  1.051199  0.192167 -1.500187 -0.357033
1 -0.509266 -1.345325 -1.281407  1.546608
2 -1.704608  0.413110 -0.256528  0.713798
3  0.549814  0.793543  0.280693 -0.279466